# url 里填写自己的订阅,名称不能重复
proxy-providers:
  google2025:
    url: "test"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      ip-version: ipv6-prefer


proxies:
  - name: "直连"
    type: direct
    udp: true

mixed-port: 7891
ipv6: true
log-level: info
allow-lan: true
unified-delay: true
tcp-concurrent: true
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geodata-loader: standard
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
  asn: https://fastly.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb


global-client-fingerprint: random
profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: false
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  fallback:
    - https://dns.cloudflare.com/dns-query
    - tls://dns.google:853
    - https://1.1.1.1/dns-query
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private,apple":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "geosite:geolocation-!cn,!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"

proxy-groups:

  - name: 默认
    type: select
    proxies: [自动选择,直连,香港,台湾,日本,新加坡,韩国,美国,全部节点]

  - name: Google
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: Telegram
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: Twitter
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: 哔哩哔哩
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: 巴哈姆特
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: YouTube
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: NETFLIX
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: Spotify
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: Github
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择,直连]

  - name: Bing
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择]

  - name: OneDrive
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择]

  - name: Microsoft
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择]

  - name: AI
    type: select
    proxies:  [台湾,日本,新加坡,韩国,美国,自动选择]

  - name: OpenAi
    type: select
    proxies:  [台湾,日本,新加坡,韩国,美国,自动选择]

  - name: LocalAreaNetwork
    type: select
    proxies:  [直连]

  - name: 国内
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,韩国,美国,全部节点,自动选择]

  - name: 其他
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,韩国,美国,自动选择,直连]

  #分隔,下面是地区分组
  - name: 香港
    type: url-test
    include-all: true
    filter: "(港|HK|hk|Hong Kong|HongKong|hongkong)"

  - name: 台湾
    type: url-test
    include-all: true
    filter: "(台|新北|彰化|TW|Taiwan)"

  - name: 日本
    type: url-test
    include-all: true
    filter: "(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)"

  - name: 美国
    type: url-test
    include-all: true
    filter: "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)"

  - name: 新加坡
    type: url-test
    include-all: true
    filter: "(新加坡|坡|狮城|SG|Singapore)"

  - name: 韩国
    type: url-test
    include-all: true
    filter: "(KR|Korea|KOR|首尔|韩|韓)"

  - name: 全部节点
    type: select
    include-all: true

  - name: 自动选择
    type: url-test
    include-all: true
    tolerance: 50

rule-providers:
  AI:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/AI.yaml"
    path: ./ruleset/AI.yaml
    interval: 86400
  OpenAi:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/OpenAi.yaml"
    path: ./ruleset/OpenAi.yaml
    interval: 86400
  B_OpenAi:
    type: http
    behavior: classical
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/B_OpenAi.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Bing.yaml"
    path: ./ruleset/Bing.yaml
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: yaml
    url: "https://fastly.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ruleset/LocalAreaNetwork.yaml
    interval: 86400

rules:
  # 绕过局域网地址
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT

  # RULE-SETS
  - RULE-SET,AI,AI
  - RULE-SET,OpenAi,OpenAi
  - RULE-SET,B_OpenAi,OpenAi
  - RULE-SET,Bing,Bing
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,LocalAreaNetwork,LocalAreaNetwork

  # GEO
  - GEOIP,lan,直连,no-resolve
  - GEOSITE,github,Github
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,spotify,Spotify
  - GEOSITE,CN,国内
  - GEOSITE,geolocation-!cn,其他

  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,telegram,Telegram,no-resolve
  - GEOIP,twitter,Twitter
  - GEOIP,CN,国内
  - MATCH,其他
