mixed-port: 7890
external-controller: 0.0.0.0:9090
external-ui: ui
log-level: error
geodata-mode: true
tcp-concurrent: true
mode: rule
allow-lan: true
bind-address: '*'
ipv6: true
interface-name: eth0
find-process-mode: always
global-client-fingerprint: random

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
    HTTP:

tun:
  enable: true
  device: meta
  stack: system
  auto-redir: true
  auto-route: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - 10.0.0.1
  nameserver:
    - 10.0.0.1
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - tls://223.5.5.5

proxy-providers:
  service-provider:
    type: http
    path: proxy/service-provider.yaml
    url: https://service-provider.com/subscribe
    interval: 3600

  homelab:
    type: file
    path: proxy/homelab.yaml

proxy-groups:
  - name: ALL
    type: select
    use: 
      - service-provider
      - homelab
    proxies:
      - DIRECT

  - name: PROXY
    type: url-test
    interval: 300
    filter: 'SG'
    use:
      - homelab

  - name: NETFLIX
    type: url-test
    interval: 300
    use:
      - kev

  - name: HOMELAB-SG
    type: url-test
    interval: 300
    filter: 'SG'
    use:
      - homelab

  - name: HOMELAB-US
    type: url-test
    interval: 300
    filter: 'US'
    use:
      - homelab

  - name: HOMELAB-JP
    type: url-test
    interval: 300
    filter: 'JP'
    use:
      - homelab

  - name: ORACLE
    type: load-balance
    filter: 'oracle'
    strategy: round-robin
    use:
      - homelab

  - name: GCP
    type: load-balance
    interval: 300
    filter: 'gcp'
    strategy: round-robin
    use:
      - homelab

  - name: AWS
    type: load-balance
    interval: 300
    filter: 'aws'
    strategy: round-robin
    use:
      - homelab

  - name: WARP
    type: select
    filter: 'WARP'
    use:
      - homelab

  - name: SG
    type: url-test
    interval: 300
    filter: '新加坡'
    use:
      - service-provider

  - name: HK
    type: url-test
    interval: 300
    filter: '香港'
    use:
      - service-provider

  - name: JP
    type: url-test
    interval: 300
    filter: '日本'
    use:
      - service-provider

  - name: US
    type: url-test
    interval: 300
    filter: '美国'
    use:
      - service-provider

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ruleset/applications.yaml
    interval: 86400

rules:
  # subrules
  - SUB-RULE,(OR,((NETWORK,TCP),(NETWORK,UDP))),split
  - SUB-RULE,(OR,((NETWORK,TCP),(NETWORK,UDP))),direct
  - RULE-SET,reject,REJECT
  - MATCH,PROXY

sub-rules:
  direct:
    # BT
    - SRC-IP-CIDR,192.168.11.8/32,DIRECT

    - DOMAIN-SUFFIX,wttr.in,DIRECT
    - GEOSITE,apple,DIRECT
    - GEOSITE,category-pt,DIRECT
    - RULE-SET,apple,DIRECT
    - RULE-SET,applications,DIRECT
    - RULE-SET,cncidr,DIRECT
    - RULE-SET,icloud,DIRECT
    - RULE-SET,lancidr,DIRECT
    - RULE-SET,private,DIRECT
    - GEOIP,LAN,DIRECT
    - GEOIP,CN,DIRECT

  split:
    # openai
    - GEOSITE,openai,WARP
    - IP-CIDR,104.18.2.161/32,WARP
    - IP-CIDR,104.18.3.161/32,WARP

    - GEOSITE,netflix,NETFLIX

    - GEOIP,hk,HK
    - GEOIP,jp,JP