name: Update ACL rules

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:

      - name: set Asia/Shanghai timezone
        uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # 2. 克隆 ACL4SSR/ACL4SSR 仓库
      - name: Clone ACL4SSR/ACL4SSR repository
        run: |
          git clone --depth 1 --branch master https://github.com/ACL4SSR/ACL4SSR.git
          pwd
          ls -la
      # 3. 移动 Clash/config 目录到当前仓库根目录
      - name: Move Clash/config directory
        run: |
          
          pwd
          cp -rf ./ACL4SSR/Clash/config ./config
          rm -rf ./ACL4SSR

      # 4. 更新自身仓库
      - name: Push changes to the current repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "GitHub-Actions@github.com"
          git add .
          git commit -m "Auto Commit"
          git push origin main  # 或者其他分支