name: Update ACL rules

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:

      - name: set Asia/Shanghai timezone
        uses: szenius/set-timezone@v1.2 # 设置虚拟环境的时区，可更改时区
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout specific folder using SVN
        run: |
          ls -la
          
          pwd

          mkdir -p ./acl4ssr_clash_config

          mkdir -p ../ACL4SSR

          cd ../ACL4SSR

          git clone -b master https://github.com/ACL4SSR/ACL4SSR.git .

          pwd

          ls -la




        

    # - name: Set up Git for committing
    #   run: |
    #     git config --global user.name "GitHub Actions"
    #     git config --global user.email "github-actions@users.noreply.github.com"

    # - name: Commit and push changes
    #   run: |
    #     # 添加下载的文件夹到 git 索引
    #     git add ./downloaded_files

    #     # 提交文件
    #     git commit -m "Add downloaded files"

    #     # 推送提交到当前仓库
    #     git push origin HEAD:main  # 如果你的默认分支是 `main`
